services:
  - type: web
    name: four-one-pos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: four-one-pos-db
          property: connectionString

databases:
  - name: four-one-pos-db
    plan: free